-- MySQL Script generated by MySQL Workbench
-- Fri May 16 22:48:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema farmaciasguadalajara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmaciasguadalajara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmaciasguadalajara` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `farmaciasguadalajara` ;

-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`categorias` (
  `idCategorias` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`proveedores` (
  `idProveedores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`unidades` (
  `idUnidades` INT NOT NULL,
  `nombreUnidad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUnidades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`articulos` (
  `idArticulos` CHAR(13) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precioUnitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `fechaVencimiento` DATE NULL DEFAULT NULL,
  `costo` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_idCategorias` INT NULL DEFAULT NULL,
  `fk_idProveedores` INT NULL DEFAULT NULL,
  `fk_idUnidades` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idArticulos`),
  INDEX `fk_idCategorias` (`fk_idCategorias` ASC) VISIBLE,
  INDEX `fk_idProveedores` (`fk_idProveedores` ASC) VISIBLE,
  INDEX `fk_idUnidades` (`fk_idUnidades` ASC) VISIBLE,
  CONSTRAINT `articulos_ibfk_1`
    FOREIGN KEY (`fk_idCategorias`)
    REFERENCES `farmaciasguadalajara`.`categorias` (`idCategorias`),
  CONSTRAINT `articulos_ibfk_2`
    FOREIGN KEY (`fk_idProveedores`)
    REFERENCES `farmaciasguadalajara`.`proveedores` (`idProveedores`),
  CONSTRAINT `articulos_ibfk_3`
    FOREIGN KEY (`fk_idUnidades`)
    REFERENCES `farmaciasguadalajara`.`unidades` (`idUnidades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`clientes` (
  `telefono` CHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`telefono`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`sucursales` (
  `idSucursales` INT NOT NULL,
  `nombreSucursal` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSucursales`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`empleados` (
  `telefono` CHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `puesto` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `sucursales` INT NULL DEFAULT NULL,
  `contra` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`telefono`),
  INDEX `sucursales` (`sucursales` ASC) VISIBLE,
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`sucursales`)
    REFERENCES `farmaciasguadalajara`.`sucursales` (`idSucursales`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`pagos` (
  `idPagos` INT NOT NULL AUTO_INCREMENT,
  `montoPago` DECIMAL(10,2) NULL DEFAULT NULL,
  `fechaPago` DATETIME NULL DEFAULT NULL,
  `metodoPago` VARCHAR(45) NULL DEFAULT NULL,
  `estadoPago` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPagos`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`pagos_backup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`pagos_backup` (
  `idPagos` INT NOT NULL,
  `montoPago` DECIMAL(10,2) NULL DEFAULT NULL,
  `fechaPago` DATETIME NULL DEFAULT NULL,
  `metodoPago` VARCHAR(45) NULL DEFAULT NULL,
  `estadoPago` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `fechaVenta` DATE NULL DEFAULT NULL,
  `montoTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_idClientes` CHAR(10) NULL DEFAULT NULL,
  `fk_idEmpleados` CHAR(10) NULL DEFAULT NULL,
  `fk_idPagos` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_idClientes` (`fk_idClientes` ASC) VISIBLE,
  INDEX `fk_idEmpleados` (`fk_idEmpleados` ASC) VISIBLE,
  INDEX `fk_pagos_ventas` (`fk_idPagos` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_ventas`
    FOREIGN KEY (`fk_idPagos`)
    REFERENCES `farmaciasguadalajara`.`pagos` (`idPagos`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`fk_idClientes`)
    REFERENCES `farmaciasguadalajara`.`clientes` (`telefono`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`fk_idEmpleados`)
    REFERENCES `farmaciasguadalajara`.`empleados` (`telefono`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmaciasguadalajara`.`ventas_backup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaciasguadalajara`.`ventas_backup` (
  `idVentas` INT NOT NULL DEFAULT '0',
  `fechaVenta` DATE NULL DEFAULT NULL,
  `montoTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `fk_idClientes` CHAR(10) NULL DEFAULT NULL,
  `fk_idEmpleados` CHAR(10) NULL DEFAULT NULL,
  `fk_idPagos` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
