-- MySQL Script generated by MySQL Workbench
-- Wed May 28 02:23:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema farmacia_guadalajara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia_guadalajara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia_guadalajara` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `farmacia_guadalajara` ;

-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`articulos` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`articulos` (
  `idArticulo` CHAR(13) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `costo` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `idCategoria` INT NULL DEFAULT NULL,
  `idUnidad` INT NULL DEFAULT NULL,
  `idProveedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `idCategoria` (`idCategoria` ASC) VISIBLE,
  INDEX `idUnidad` (`idUnidad` ASC) VISIBLE,
  INDEX `idProveedor` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `articulos_ibfk_1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `farmacia_guadalajara`.`categorias` (`idCategoria`),
  CONSTRAINT `articulos_ibfk_2`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `farmacia_guadalajara`.`unidades` (`idUnidad`),
  CONSTRAINT `articulos_ibfk_3`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `farmacia_guadalajara`.`proveedores` (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`categorias` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`clientes` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`clientes` (
  `idCliente` CHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `comprasTotales` INT NULL DEFAULT '0',
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`compras` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`compras` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idProveedor` INT NULL DEFAULT NULL,
  `fechaCompra` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCompra`),
  INDEX `idProveedor` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `compras_ibfk_1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `farmacia_guadalajara`.`proveedores` (`idProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`detallecompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`detallecompra` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`detallecompra` (
  `idDetalleCompra` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NULL DEFAULT NULL,
  `idArticulo` CHAR(13) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precioUnitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  INDEX `idCompra` (`idCompra` ASC) VISIBLE,
  INDEX `idArticulo` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `detallecompra_ibfk_1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `farmacia_guadalajara`.`compras` (`idCompra`),
  CONSTRAINT `detallecompra_ibfk_2`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `farmacia_guadalajara`.`articulos` (`idArticulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`detalleventa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`detalleventa` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`detalleventa` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idVenta` INT NULL DEFAULT NULL,
  `idArticulo` CHAR(13) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precioUnitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `subtotal` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `idVenta` (`idVenta` ASC) VISIBLE,
  INDEX `idArticulo` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `detalleventa_ibfk_1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `farmacia_guadalajara`.`ventas` (`idVenta`),
  CONSTRAINT `detalleventa_ibfk_2`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `farmacia_guadalajara`.`articulos` (`idArticulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`empleados` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`empleados` (
  `idEmpleado` CHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `puesto` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `idSucursal` INT NULL DEFAULT NULL,
  `ventasRealizadas` INT NULL DEFAULT '0',
  PRIMARY KEY (`idEmpleado`),
  INDEX `idSucursal` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `farmacia_guadalajara`.`sucursales` (`idSucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`pagos` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`pagos` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `idVenta` INT NULL DEFAULT NULL,
  `metodoPago` VARCHAR(50) NULL DEFAULT NULL,
  `monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `fechaPago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPago`),
  INDEX `idVenta` (`idVenta` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `farmacia_guadalajara`.`ventas` (`idVenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`sucursales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`sucursales` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`sucursales` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `telefono` CHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`unidades` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`unidades` (
  `idUnidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUnidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `farmacia_guadalajara`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia_guadalajara`.`ventas` ;

CREATE TABLE IF NOT EXISTS `farmacia_guadalajara`.`ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fechaVenta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idCliente` CHAR(10) NULL DEFAULT NULL,
  `idEmpleado` CHAR(10) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idCliente` (`idCliente` ASC) VISIBLE,
  INDEX `idEmpleado` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `farmacia_guadalajara`.`clientes` (`idCliente`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `farmacia_guadalajara`.`empleados` (`idEmpleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
